// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmtxlyxgpmszsqfuyzkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdHhseXhncG1zenNxZnV5emtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDYzNDAsImV4cCI6MjA3MTUyMjM0MH0.DGkpILXtrObio5GZ0DT_1GlXCNL7F2fYzqJcYvNlbbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});